import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./Component/Navbar/Navbar";
import Footer from "./Component/Footer/Footer";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar></Navbar>
          <div className="container mx-auto">{children}</div>
          <Footer></Footer>
          <Toaster></Toaster>
        </AuthProvider>
      </body>
    </html>
  );
}
